import { useEffect, useMemo, useState } from 'react';
import { MoreHorizontal, Plus, ShieldCheck, UserCheck, UserRound, UserRoundX } from 'lucide-react';
import { createUser, getCurrentUser, getUsers, updateUser, updateUserStatus } from '../services/api';
import Modal from '../components/Modal';
import { Avatar, FilterBar, PageHeader, StatCard, StatusBadge } from '../components/PremiumUI';

const emptyForm = { prenom: '', nom: '', email: '', role: 'utilisateur', mot_de_passe: '1234' };
const Users = () => {
    const [users, setUsers] = useState([]); const [search, setSearch] = useState(''); const [form, setForm] = useState(emptyForm); const [selected, setSelected] = useState(null); const [modal, setModal] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const current = getCurrentUser();
    useEffect(() => { getUsers().then((result) => setUsers(result.users || [])).catch((err) => setError(err.message || 'Impossible de charger les utilisateurs.')).finally(() => setLoading(false)); }, []);
    const filtered = useMemo(() => users.filter((user) => `${user.prenom} ${user.nom} ${user.email} ${user.role}`.toLowerCase().includes(search.toLowerCase())), [users, search]);
    const openCreate = () => { setSelected(null); setForm(emptyForm); setModal(true); }; const openEdit = (user) => { setSelected(user); setForm({ prenom: user.prenom, nom: user.nom, email: user.email, role: user.role, mot_de_passe: '' }); setModal(true); };
    const save = async (event) => { event.preventDefault(); setError(''); try { const result = selected ? await updateUser(selected.id, form) : await createUser(form); setUsers((items) => selected ? items.map((item) => item.id === selected.id ? result.user : item) : [result.user, ...items]); setModal(false); setMessage(selected ? 'Utilisateur mis à jour.' : 'Utilisateur créé.'); } catch (err) { setError(err.message || 'Impossible d’enregistrer cet utilisateur.'); } };
    const toggleStatus = async (user) => { try { const result = await updateUserStatus(user.id, !user.actif); setUsers((items) => items.map((item) => item.id === user.id ? result.user : item)); } catch (err) { setError(err.message || 'Impossible de modifier le statut.'); } };
    const active = users.filter((user) => user.actif !== false).length;
    return <div className="page-shell"><PageHeader eyebrow="Administration" title="Utilisateurs" subtitle="Gérez les comptes et les accès de la plateforme SRTB." actions={<button className="btn-primary" type="button" onClick={openCreate}><Plus size={16} /> Ajouter un utilisateur</button>} />
        {error && <div className="error-message">{error}</div>}{message && <div className="success-message">{message}</div>}
        <div className="admin-stats"><StatCard icon={<UserRound size={17} />} label="Total utilisateurs" value={users.length} hint="Comptes enregistrés" /><StatCard icon={<UserCheck size={17} />} label="Comptes actifs" value={active} hint="Accès autorisés" tone="teal" /><StatCard icon={<ShieldCheck size={17} />} label="Administrateurs" value={users.filter((user) => user.role === 'admin').length} hint="Accès opérations" tone="slate" /></div>
        <FilterBar search={search} onSearch={setSearch} placeholder="Rechercher par nom ou email..."><span className="table-result-count">{filtered.length} résultat{filtered.length > 1 ? 's' : ''}</span></FilterBar>
        <div className="surface admin-table-wrap">{loading ? <div className="premium-skeleton" /> : <table className="premium-table"><thead><tr><th>Utilisateur</th><th>Email</th><th>Rôle</th><th>Statut</th><th>Inscription</th><th /></tr></thead><tbody>{filtered.map((user) => <tr key={user.id}><td><div className="table-person"><Avatar name={`${user.prenom} ${user.nom}`} size="sm" /><strong>{user.prenom} {user.nom}</strong></div></td><td>{user.email}</td><td><span className="role-chip">{user.role === 'admin' ? 'Administrateur' : 'Utilisateur'}</span></td><td><StatusBadge status={user.actif === false ? 'refusee' : 'actif'} /></td><td>{user.dateCreation || '-'}</td><td><div className="table-actions"><button className="icon-button" type="button" onClick={() => openEdit(user)} aria-label={`Modifier ${user.nom}`}><MoreHorizontal size={17} /></button><button className="table-text-action" type="button" disabled={user.id === current?.id} onClick={() => toggleStatus(user)}>{user.actif === false ? 'Activer' : 'Désactiver'}</button></div></td></tr>)}</tbody></table>}</div>
        <Modal visible={modal} title={selected ? 'Modifier l’utilisateur' : 'Nouvel utilisateur'} onClose={() => setModal(false)} actions={<><button className="btn-secondary" type="button" onClick={() => setModal(false)}>Annuler</button><button className="btn-primary" type="submit" form="user-form">Enregistrer</button></>}><form id="user-form" className="modal-form" onSubmit={save}><div className="profile-form-grid"><label className="premium-field"><span>Prénom</span><input value={form.prenom} required onChange={(event) => setForm({ ...form, prenom: event.target.value })} /></label><label className="premium-field"><span>Nom</span><input value={form.nom} required onChange={(event) => setForm({ ...form, nom: event.target.value })} /></label><label className="premium-field field-wide"><span>Email</span><input type="email" value={form.email} required onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label className="premium-field"><span>Rôle</span><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="utilisateur">Utilisateur</option><option value="admin">Administrateur</option></select></label></div></form></Modal>
    </div>;
};
export default Users;
